name: audit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
  - cron: '0 12 * * *' # every day at noon

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: npm audit --production
  codeql:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: github/codeql-action/init@main
    - uses: github/codeql-action/analyze@main
